from setuptools import setup, find_packages

setup(
    name="guardianlink",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "fastapi>=0.108.0",
        "uvicorn>=0.24.0",
        "pydantic>=2.5.2",
        "python-dotenv>=1.0.0",
        "langchain>=0.1.5",
        "langchain-core>=0.1.14",
        "langchain-openai>=0.0.5",
        "langchain-community>=0.0.15",
        "langgraph>=0.0.20",
        "openai>=1.3.5",
        "faiss-cpu>=1.7.4",
        "web3>=6.11.3",
        "python-multipart>=0.0.6",
        "httpx>=0.25.2",
        "tenacity>=8.2.3",
        "pytest>=7.4.0",
        "pytest-cov>=4.1.0",
    ],
    python_requires=">=3.9",
    author="The Bulls Team",
    author_email="team@thebulls.example.com",
    description="AI-Driven Crisis Response & Mental Health Protocol",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/theBulls/GuardianLink",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
